events {
    worker_connections 1024;
}

http {
    upstream backend {
        server app:3000;
    }

    server {
        listen 80;
        # Replace with your actual EC2 IP
        server_name app.18.143.227.177.nip.io;

        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # You can even point Grafana/Prometheus here later if you want
    server {
        listen 80;
        server_name monitor.18.143.227.177.nip.io;

        location / {
            proxy_pass http://grafana:3000;
            proxy_set_header Host $host;
        }
    }
}